name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Check Architecture Build Settings
      run: xcodebuild -project iOS/easter-pixel.xcodeproj -target "easter-pixel" -showBuildSettings | grep -E "ARCHS|ONLY_ACTIVE_ARCH|SUPPORTED_PLATFORMS|VALID_ARCHS|SDKROOT|TARGETED_DEVICE_FAMILY"

    - name: Set iOS Deployment Target
      run: sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 10.0;/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/' iOS/easter-pixel.xcodeproj/project.pbxproj

    - name: List Xcode Schemes
      run: xcodebuild -project iOS/easter-pixel.xcodeproj -list

    - name: Build iOS project for Simulator
      run: xcodebuild -project iOS/easter-pixel.xcodeproj -scheme easter-pixel -configuration Development -archivePath iOS/easter-pixel.xcarchive archive -destination "platform=iOS Simulator,name=iPhone 15 Pro Max" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export IPA
      run: |
        mkdir -p build
        xcodebuild -exportArchive \
          -archivePath iOS/easter-pixel.xcarchive \
          -exportPath build \
          -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Ipa
        path: iOS/easter-pixel.ipa # Adjust if your app bundle identifier is different